### ISSUE TITLE
Adding img file infos?

### ISSUE THREAD

**Issue by EmTee70** [dd86k/dfile#2]
Would be nice to get the infos of image files (.png, .gif, .jpg) 
like the output of  "identify -ping" from ImageMagic 
especially the size in pixels. 
+ detecting rgb or cmyc .jpg 
+ additional meta data as date and other .jpg infos.
but this might result in a very long todo-list.

**Comment by dd86k** [comment]
That would be interesting to add especially with the `--more` switch.

Though yeah, it does seems like a nasty to-do task. Especially since I have to get understandable documentation (standard papers) of the most popular images and figure out the colour palettes and all, despite this tool not focusing on this kind of information (likely outside the metadata).

However I'm certain it will bring usefulness to the program, so I'll add that in eventually.

**Comment by dd86k** [comment]
Hello again,

Today I roughly implemented the PNG scanner. I only played with imagemagic once to dissect an image, so I don't know what exactly information it displays, but here's an example:

```
D:\DOCUMENTS\D projects\dfile>dfile -m tests\asciifull.png
Portable Network Graphics image (PNG)
715x823 pixels, RGBA 24-bit depth, Default compression, Default filtering, No interla
cing

D:\DOCUMENTS\D projects\dfile>
```

Hopefully it will satisfy you despite PNGs palettes are only available with a color type of 3 (PLTE chunk).

**Comment by dd86k** [comment]
Closing this as there is enough information from image files. More information for FLIF and BPG images are planned, but this tool is not supposed to be like ImageMagic.
